name: ci
on: [push]
jobs:
  build_and_test:
    name: Build and test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          updateAssemblyInfo: true

      - run: dotnet build ${{ github.workspace }}/src
      
      - run: dotnet test ${{ github.workspace }}/src --no-build

      - run: "docker build $GITHUB_WORKSPACE/src/Ursa -t ursa:${{ steps.version_step.outputs.fullSemVer }}" 

  # push:
  #   name: Push images
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   steps:
  #     - run: docker push