name: ci
on: [push, pull_request]

env:
  IMAGE_ID: ghcr.io/lulzhipsters/ursa

permissions:
  contents: read
  packages: write

jobs:
  build_test_push:
    name: Build and test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          updateAssemblyInfo: true

      - run: dotnet build ${{ github.workspace }}/src
      
      - run: dotnet test ${{ github.workspace }}/src --no-build

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: >- 
          docker build ${{ github.workspace }}/src/Ursa
          -t $IMAGE_ID:${{ steps.version_step.outputs.majorMinorPatch }}
          -t $IMAGE_ID:${{ steps.version_step.outputs.major }}
          -t $IMAGE_ID:${{ steps.version_step.outputs.major }}.${{ steps.version_step.outputs.minor }}
          -t $IMAGE_ID:latest

      - run: docker push $IMAGE_ID
        if: ${{ startsWith(github.ref,'refs/tags/v') }}